update build script to match new `ocw-to-hugo` output structure and add verbose switch
mitodl/ocw-course-hugo-starter pull request #25
Opened 2021-03-08 18:00 UTC by gumaerc

#### What are the relevant tickets?
Related to https://github.com/mitodl/ocw-to-hugo/issues/214
Closes https://github.com/mitodl/ocw-course-hugo-starter/issues/8

#### What's this PR do?
This PR updates the build script to match the new `ocw-to-hugo` output structure that's changed by [this](https://github.com/mitodl/ocw-to-hugo/pull/216) PR.  It also makes the output quiet by default and adds a verbose switch to turn it back on for testing / debugging.

#### How should this be manually tested?
 - Follow the instructions in [this](https://github.com/mitodl/ocw-to-hugo/pull/216) PR to generate markdown
 - Spin up `ocw-www` locally
 - Run `./build.sh -o ~/Code/ocw-www/site/public -c ~/Code/ocw-to-hugo/private/output -b http://localhost:3000/courses`
 - Browse to a test course locally running under `ocw-www` and ensure it renders correctly, for example: http://localhost:3000/courses/6-034-artificial-intelligence-fall-2010/
 - Run `./build.sh -o ~/Code/ocw-www/site/public -c ~/Code/ocw-to-hugo/private/output -b http://localhost:3000/courses -v` and ensure the same process works, but you should see verbose output when rendering the hugo sites

2021-03-09 18:02 UTC, noisecapella requested changes

2021-03-09 18:02 UTC, noisecapella commented on build.sh
> +        if [ $VERBOSE ne true ]; then
Can we use double square brackets here for consistency? Also, I think `ne` should be `-ne`

2021-03-09 18:02 UTC, noisecapella commented on build.sh
> +        eval "cp $COURSE/data/course.json data/course.json"
I know the `eval` comes from previous code but I'm not sure it's doing anything useful here. Can we remove the `eval` and use the contents of the string directly?

2021-03-09 23:13 UTC, gumaerc commented
@noisecapella all set

2021-03-10 14:52 UTC, noisecapella approved these changes

2021-03-10 19:11 UTC, merged